# Projet Analyse donnees de these:

Analyse et exploration des donnees des centrales de production electriques du senegal

## Importation des packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
import seaborn as sns

## Chargement des donnees

In [2]:
fichier_excel = r"F:\Mes_Documents_de_these\DOCUMENTS_RECHERCHE\DOCUMENTS_DE_REPPORTS\Datasets_theses\Rapports2019\01janvier2019\01012019Ma.xlsx" # le chemain du fichier 
donnees = pd.read_excel(fichier_excel,sheet_name=None) # lecture du fichier avec tous les feuilles selon (sheet_name= None)

In [3]:
print("feuilles disponibles")
donnees.keys() # la liste des feuilles  contenues dans ce classeur excel

feuilles disponibles

dict_keys(['Rapport', 'Centrales', 'Demande', 'Délestage', 'P Inst', 'Energie', 'Pdel', 'Pdispo', 'Clients HT', 'liens', 'Reseau', 'Feuil1'])

In [4]:
dossier = r"F:\Mes_Documents_de_these\DOCUMENTS_RECHERCHE\DOCUMENTS_DE_REPPORTS\Datasets_theses\Rapports2019\01janvier2019"

# liste des fichiers contenus dans le dossier du mois de janvier avec elimination des extentions non conformes
fichiers_excel1 = [f for f in os.listdir(dossier) if f.endswith(".xlsx") and not f.startswith("~$")]

### Extraction des donnees de les Demande energetique

In [5]:
def nettoyage_demande(dossier,fichiers_excel1,cellule):
    liste_demande = []
    for fichier in fichiers_excel1:
        
        chemin_complet = os.path.join(dossier, fichier) # pour avoir le chemin complet
        
        classeur = pd.read_excel(chemin_complet,sheet_name=None)
        
        for feuilles in classeur.keys():
            
            if feuilles == cellule: #'Demande':
        
                Demande = classeur[feuilles]

                Demande.columns  = classeur[feuilles].iloc[1]

                Demande = Demande[2:].reset_index(drop=True)[:27]

                Demande = Demande.loc[:,list(Demande.columns[:5])]
                liste_demande.append(Demande)
        Demande_2019 = pd.concat(liste_demande,axis=0)
    return Demande_2019 

Demande_janvier = nettoyage_demande(dossier,fichiers_excel1,'Demande')
Demande_janvier.head()

1 Heure Puis. Dispo Puis TAG couplée     Demande    Fréq
0   1 h  636.930263                0  430.407707  50.109
1   2 h  636.930263                0  406.129563  49.939
2   3 h  636.930263                0  372.603857  50.281
3   4 h  636.930263                0     356.614  50.365
4   5 h  636.930263                0  352.424888  50.199

In [6]:
Demande_janvier.shape

(837, 5)

### Rapport des delestages

In [7]:
def nottoyage_delestage(dossier,fichiers_excel1,cellule):
    liste_Délestage = []
    for fichier in fichiers_excel1:
        
        chemin_complet = os.path.join(dossier, fichier) # pour avoir le chemin complet
        
        classeur = pd.read_excel(chemin_complet,sheet_name=None)
        
        for feuilles in classeur.keys():
            
            if feuilles == cellule:
        
                Délestage = classeur[feuilles]

                Délestage.columns  = classeur[feuilles].iloc[1]
                
                Délestage =  Délestage[2:].reset_index(drop=True)[:27]
                
                Délestage = Délestage[Délestage.columns[:7]]
                
                liste_Délestage.append( Délestage) 
                
        Délestage = pd.concat(liste_Délestage,axis=0)
    return Délestage

delestage_janvier = nottoyage_delestage(dossier,fichiers_excel1,'Délestage')

In [8]:
delestage_janvier.shape

(837, 7)

In [9]:
delestage_janvier.head()

1,Heure,P.dispo (MW),Demande (MW),Délest par Manque Product,P. Effacée (MW),Autres P. coupée (MW),Déficit total (MW)
0,1 h,636.930263,430.407707,0,0,0,0
1,2 h,636.930263,406.129563,0,0,0,0
2,3 h,636.930263,372.603857,0,0,0,0
3,4 h,636.930263,356.614,0,0,3.3,3.3
4,5 h,636.930263,352.424888,0,0,0,0

### Extraction des donnees de les centrales

In [10]:
def Nettoyage_centrale(dossier,fichiers_excel,cellule):
    liste_centrales = []
    for fichier in fichiers_excel:
        
        chemin_complet = os.path.join(dossier, fichier) # pour avoir le chemin complet
        
        classeur = pd.read_excel(chemin_complet,sheet_name=None) # Importation du classeur avec toutes les feuilles
        
        for feuilles in classeur.keys(): # iteration sur les feuilles du classeur
            
            if feuilles == cellule: # comparaison avec la feuille du nom de la cellule
        
                Centrale = classeur[feuilles] # recuperation du dataframe 

                Centrale.columns = Centrale.iloc[1] # Définir la première ligne restante comme en-têtes 

                Centrale = Centrale[2:].reset_index(drop=True)[:27] # Supprimer les deux premieres ligne apres l'en tetes
                
                liste_centrales.append(Centrale)
        
        # concatenation de l'ensemble des dataframe pour le mois de janvier        
        Centrales = pd.concat(liste_centrales,axis=0)
    return Centrales

In [11]:
centrales = Nettoyage_centrale(dossier,fichiers_excel1,'Centrales')
centrales.shape

(837, 28)

In [12]:
centrales.head()

1,Heure,C6,C7,kah 1,Manantali,GTI,Somelec,Kounoune,Agg edm,APR,...,PV Bokhol,PV Sakal,PV Mbour,PV Merina Mekhé,PV Santhiou Mekhé,PV Kahone,Total PV,PV DIASS,NaN,NaN
0,1 h,82.3,78.2,0,9.365707,0,0,29.8,0,106.9,...,0,0,0,0,0,0,0,0,NaN,12.7
1,2 h,83.2,78.2,0,19.677563,0,0,29.8,0,75.2,...,0,0,0,0,0,0,0,0,NaN,NaN
2,3 h,82.2,77.8,0,17.521857,0,0,29.8,0,73.9,...,0,0,0,0,0,0,0,0,NaN,NaN
3,4 h,68.4,62.3,0,0,0,0,29.8,0,77.2,...,0,0,0,0,0,0,0,0,NaN,NaN
4,5 h,68.3,52.2,0,24.902888,0,0,29.8,0,75.1,...,0,0,0,0,0,0,0,0,NaN,NaN

### Extraction de la feuille Energie

In [13]:
def nettoyages_energie(dossier,fichiers_excel1,cellule):
    liste_Pdispo = []
    pv_production = ['PV-Mbour','PV-CICAD','PV Kahone','PV-Bokhol','PV Mékhé Mérina',
                                     'PV S Mekhe Santhiou','PV Sakal']
    for fichier in fichiers_excel1:
        
        chemin_complet = os.path.join(dossier, fichier) # pour avoir le chemin complet
        
        classeur = pd.read_excel(chemin_complet,sheet_name=None)
        
        for feuilles in classeur.keys():
            
            if feuilles == cellule:
        
                Pdispo = classeur[feuilles]
                
                Pdispo = Pdispo[pv_production]
                
                Pdispo  = Pdispo.iloc[:24]
                
                liste_Pdispo.append( Pdispo) 
                
        energie  = pd.concat(liste_Pdispo,axis=0,ignore_index=True)
        
    return energie

In [14]:
energie_janvier = nettoyages_energie(dossier,fichiers_excel1,'Energie')
energie_janvier.head()

,PV-Mbour,PV-CICAD,PV Kahone,PV-Bokhol,PV Mékhé Mérina,PV S Mekhe Santhiou,PV Sakal
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
energie_janvier.shape

(744, 7)

In [16]:
pv_sources = list(energie_janvier.columns[20:24])+list(energie_janvier.columns[26:28])+list(energie_janvier.columns[29:30])

pv_sources

[]

In [17]:
energie_janvier[pv_sources].head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

## Recuperation des donnees annuelle 2019

### Extraction des donnees de les Demande energetique

In [18]:
chemin = r"F:\Mes_Documents_de_these\DOCUMENTS_RECHERCHE\DOCUMENTS_DE_REPPORTS\Datasets_theses\Rapports2019" 

listes_demande = []
for racine, dossiers, fichiers in os.walk(chemin):
    
    for dossier in dossiers:
        
        chemin_complete = os.path.join(racine, dossier)
        # liste des fichiers contenus dans le dossier du mois de janvier avec elimination des extentions non conformes
        fichiers_excel1 = [f for f in os.listdir(chemin_complete) if f.endswith(".xlsx") and not f.startswith("~$")]
        Demande = nettoyage_demande(chemin_complete,fichiers_excel1,'Demande')
        listes_demande.append(Demande)
Demande_annuelle2019 = pd.concat(listes_demande,axis=0)

c:\ProgramData\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

In [19]:
Demande_annuelle2019.head()

1 Heure Puis. Dispo Puis TAG couplée     Demande    Fréq
0   1 h  636.930263                0  430.407707  50.109
1   2 h  636.930263                0  406.129563  49.939
2   3 h  636.930263                0  372.603857  50.281
3   4 h  636.930263                0     356.614  50.365
4   5 h  636.930263                0  352.424888  50.199

In [20]:
Demande_annuelle2019.shape

(9774, 5)

### delestage de la senelec durant l'annnee 2019

In [35]:
chemin = r"F:\Mes_Documents_de_these\DOCUMENTS_RECHERCHE\DOCUMENTS_DE_REPPORTS\Datasets_theses\Rapports2019" 

listes_delestage = []
for racine, dossiers, fichiers in os.walk(chemin):
    
    for dossier in dossiers:
        
        chemin_complete = os.path.join(racine, dossier)
        # liste des fichiers contenus dans le dossier du mois de janvier avec elimination des extentions non conformes
        fichiers_excel1 = [f for f in os.listdir(chemin_complete) if f.endswith(".xlsx") and not f.startswith("~$")]
        delestage = nottoyage_delestage(chemin_complete,fichiers_excel1,'Délestage')
        listes_delestage.append(delestage)
Delestage_annuelle_2019 = pd.concat(listes_delestage,axis=0)

Delestage_annuelle_2019.head()

c:\ProgramData\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

1,Heure,P.dispo (MW),Demande (MW),Délest par Manque Product,P. Effacée (MW),Autres P. coupée (MW),Déficit total (MW)
0,1 h,636.930263,430.407707,0,0,0,0
1,2 h,636.930263,406.129563,0,0,0,0
2,3 h,636.930263,372.603857,0,0,0,0
3,4 h,636.930263,356.614,0,0,3.3,3.3
4,5 h,636.930263,352.424888,0,0,0,0

In [36]:
Delestage_annuelle_2019.shape

(9774, 7)

In [37]:
heures = pd.date_range(start='01-01-2019 01:00:00', periods=9774, freq='H')

C:\Users\Abdoulaye_Faye\AppData\Local\Temp\ipykernel_9548\72191681.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  heures = pd.date_range(start='01-01-2019 01:00:00', periods=9774, freq='H')

In [40]:
heures.values

array(['2019-01-01T01:00:00.000000000', '2019-01-01T02:00:00.000000000',
       '2019-01-01T03:00:00.000000000', ...,
       '2020-02-12T04:00:00.000000000', '2020-02-12T05:00:00.000000000',
       '2020-02-12T06:00:00.000000000'], dtype='datetime64[ns]')

In [38]:
Delestage_annuelle_2019['Frequence (Hz)'] = Demande_annuelle2019['Fréq']

Delestage_annuelle_2019.head()

1,Heure,P.dispo (MW),Demande (MW),Délest par Manque Product,P. Effacée (MW),Autres P. coupée (MW),Déficit total (MW),Frequence (Hz)
0,1 h,636.930263,430.407707,0,0,0,0,50.109
1,2 h,636.930263,406.129563,0,0,0,0,49.939
2,3 h,636.930263,372.603857,0,0,0,0,50.281
3,4 h,636.930263,356.614,0,0,3.3,3.3,50.365
4,5 h,636.930263,352.424888,0,0,0,0,50.199

In [41]:
Delestage_annuelle_2019['Heure'] = heures.values

In [43]:
Delestage_annuelle_2019.head()

1,Heure,P.dispo (MW),Demande (MW),Délest par Manque Product,P. Effacée (MW),Autres P. coupée (MW),Déficit total (MW),Frequence (Hz)
0,2019-01-01 01:00:00,636.930263,430.407707,0,0,0,0,50.109
1,2019-01-01 02:00:00,636.930263,406.129563,0,0,0,0,49.939
2,2019-01-01 03:00:00,636.930263,372.603857,0,0,0,0,50.281
3,2019-01-01 04:00:00,636.930263,356.614,0,0,3.3,3.3,50.365
4,2019-01-01 05:00:00,636.930263,352.424888,0,0,0,0,50.199

In [44]:
Delestage_annuelle_2019.to_excel('Delestage_annuelle_2019.xlsx',index=False)

### la production des Centrales durant l'année 2019

In [23]:
listes_centrales = []
for racine, dossiers, fichiers in os.walk(chemin):
    
    for dossier in dossiers:
        
        chemin_complete = os.path.join(racine, dossier)
        
        # liste des fichiers contenus dans le dossier du mois de janvier avec elimination des extentions non conformes
        fichiers_excel1 = [f for f in os.listdir(chemin_complete) if f.endswith(".xlsx") and not f.startswith("~$")]
        
        # regroupement des données des centrales
        centrales = Nettoyage_centrale(chemin_complete,fichiers_excel1,'Centrales')
        listes_centrales.append(centrales)
        
centrales_annuelle_2019 = pd.concat(listes_centrales,axis=0)

centrales_annuelle_2019.head()

c:\ProgramData\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

1,Heure,C6,C7,kah 1,Manantali,GTI,Somelec,Kounoune,Agg edm,APR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,1 h,82.3,78.2,0,9.365707,0,0,29.8,0,106.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2 h,83.2,78.2,0,19.677563,0,0,29.8,0,75.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3 h,82.2,77.8,0,17.521857,0,0,29.8,0,73.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4 h,68.4,62.3,0,0,0,0,29.8,0,77.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5 h,68.3,52.2,0,24.902888,0,0,29.8,0,75.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
centrales_annuelle_2019.shape

(9774, 483)

In [25]:
centrales = Nettoyage_centrale(chemin_complete,fichiers_excel1,'Centrales')

In [26]:
centrales.head()

1,Heure,C6,C7,kah 1,Manantali,Agg1,Agg2,Somelec,Kounoune,APR CDB,...,PV Sakal,PV Mbour,PV Merina Mekhé,PV Santhiou Mekhé,PV Kahone,Total PV,PV DIASS,PV CICAD,NaN,NaN
0,1 h,85.7,7.1,0,12.231996,0,0,0,7.1,0,...,0,0,0,0,0,0,0,0,NaN,12.7
1,2 h,70.71,7.1,0,37.03447,0,0,0,7.1,0,...,0,0,0,0,0,0,0,0,NaN,NaN
2,3 h,70.6,7.1,0,34.639316,0,0,0,7.1,0,...,0,0,0,0,0,0,0,0,NaN,NaN
3,4 h,70.6,7.1,0,35.088146,0,0,0,7.1,0,...,0,0,0,0,0,0,0,0,NaN,NaN
4,5 h,57.02,7.1,0,45.1933,0,0,0,7.1,0,...,0,0,0,0,0,0,0,0,NaN,NaN

In [27]:
listes_energie = []
for racine, dossiers, fichiers in os.walk(chemin):
    
    for dossier in dossiers:
        
        chemin_complete = os.path.join(racine, dossier)
        
        # liste des fichiers contenus dans le dossier du mois de janvier avec elimination des extentions non conformes
        fichiers_excel1 = [f for f in os.listdir(chemin_complete) if f.endswith(".xlsx") and not f.startswith("~$")]
        
        # regroupement des données des centrales
        energie = nettoyages_energie(chemin_complete ,fichiers_excel1,'Energie')
        
        listes_energie.append(energie)
        
energie_annuelle_2019 = pd.concat(listes_energie,axis=0)

energie_annuelle_2019.head()

c:\ProgramData\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

,PV-Mbour,PV-CICAD,PV Kahone,PV-Bokhol,PV Mékhé Mérina,PV S Mekhe Santhiou,PV Sakal
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
energie_annuelle_2019.head(30)

,PV-Mbour,PV-CICAD,PV Kahone,PV-Bokhol,PV Mékhé Mérina,PV S Mekhe Santhiou,PV Sakal
0,0.0,0.000,0.00,0.00,0.0,0.0,0.000
1,0.0,0.000,0.00,0.00,0.0,0.0,0.000
2,0.0,0.000,0.00,0.00,0.0,0.0,0.000
3,0.0,0.000,0.00,0.00,0.0,0.0,0.000
4,0.0,0.000,0.00,0.00,0.0,0.0,0.000
5,0.0,0.000,0.00,0.00,0.0,0.0,0.000
6,0.0,0.000,0.01,0.00,0.0,0.0,0.000
7,0.24716,0.012,1.01,0.06,9.2,9.7,0.036
8,2.949692,0.170,4.07,2.37,15.2,6.2,2.240
9,8.326346,0.623,7.62,6.57,11.9,12.5,6.275
10,11.8646,0.996,9.95,10.10,16.2,16.6,7.776
11,13.17636,1.296,12.82,12.40,18.6,19.1,8.112
12,13.76076,1.399,13.16,13.27,19.4,20.0,8.083
13,13.872565,1.525,12.86,13.08,18.9,19.2,8.082
14,12.63164,0.984,11.15,11.82,15.5,16.9,7.972
15,10.09156,1.090,8.30,9.73,12.5,12.7,7.612
16,6.497385,0.915,4.54,6.73,7.5,7.5,6.425
17,2.08176,0.372,1.02,2.73,1.9,1.9,3.028
18,0.72112,0.077,0.02,0.20,0.0,0.0,0.233
19,0.70444,0.000,0.00,0.00,0.0,0.0,0.000
20,0.70408,0.000,0.00,0.00,0.0,0.0,0.000
21,0.0,0.000,0.00,0.00,0.0,0.0,0.000
22,0.0,0.000,6.10,0.00,0.0,0.0,0.000
23,0.0,0.000,0.00,0.00,0.0,0.0,0.000
24,0.0,0.000,0.00,0.00,0.0,0.0,0.000
25,0.0,0.000,0.00,0.00,0.0,0.0,0.000
26,0.0,0.000,0.00,0.00,0.0,0.0,0.000
27,0.0,0.000,0.00,0.00,0.0,0.0,0.000
28,0.0,0.000,0.00,0.00,0.0,0.0,0.000
29,0.0,0.000,0.00,0.00,0.0,0.0,0.000